tests: Include missing sys/time.h
This is found when building for musl C library systems where sys/time.h
is not included indirectly and select() and timeval structs are used

Fixes

../../git/tests/receive.c:64:17: error: variable has incomplete type 'struct timeval'
   64 |         struct timeval tvSelectTimeout;
      |                        ^
../../git/tests/receive.c:64:9: note: forward declaration of 'struct timeval'
   64 |         struct timeval tvSelectTimeout;
      |                ^
../../git/tests/receive.c:67:2: error: call to undeclared function 'select'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   67 |         select(0, NULL, NULL, NULL, &tvSelectTimeout);
      |         ^